### PR TITLE
Update main.js with pt-br pronouns

### PR DESCRIPTION
**Pull request by todearaujo**
Pronouns are now translated to brazilian portuguese (pt-br). Also, I've adapt GPT sentences to this language.

### CODE REVIEW

**Comment by todearaujo** [comment]
@brianpetro, have you seen my contribution? It’s for Brazilian Portuguese language. Can you, please, see it and if it’s ok, merge? It’s literally just a couple of line in the code. Thanks!

**Comment by todearaujo** [comment]
Hi! Will you implement this translations? Do you need help with any other? I would love to help.

**Comment by brianpetro** [comment]
@todearaujo thanks for your willingness to help with the translations.

Over the next couple weeks I'll be finishing up v2.0 and moving into v2.1, where I will be addressing issues with the Smart Chat. So I should have a better idea of what will need to be done in terms of translations soon.

🌴

**Comment by todearaujo** [comment]
Great! Count me in.

**Comment by brianpetro** [comment]
Thanks for contributing this translation 😊

The latest release (`v2.3.39`) now includes 20 languages, including this one https://github.com/brianpetro/obsidian-smart-connections/releases/tag/2.3.39

🌴

**Pull request closed without merging**
